# Build settings for Next.js with Netlify
[build]
  command = "npm run netlify:build"
  publish = "out"

# Environment variables for build
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Enable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200