# Build settings for Next.js on Netlify
[build]
  publish = ".next"
  command = "npm run netlify:build"
  functions = "netlify/functions"

# Environment variables for build
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Function-specific settings
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# AI Function specific timeout (120 seconds)
[functions."binno-final-analysis"]
  timeout = 120

[functions."binno-final-analysis-quick"]
  timeout = 60

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:; media-src 'self' https:;"
    X-CTD-Deploy = "optimized-v2-ssl"

# Headers for API Functions (CORS)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Force HTTPS redirects
[[redirects]]
  from = "http://chaintalkdailyhub.com/*"
  to = "https://chaintalkdailyhub.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.chaintalkdailyhub.com/*"
  to = "https://chaintalkdailyhub.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.chaintalkdailyhub.com/*"
  to = "https://chaintalkdailyhub.com/:splat"
  status = 301
  force = true

# SPA fallback for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200