# Build settings for static export
[build]
  publish = "out"
  command = "npm run netlify:build"
  functions = "netlify/functions"

# Environment variables for build
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback for Next.js - but exclude function paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200