/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "CTDHUB_BINNOAI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CTDHUB_BINNOAI__factory>;

    getContractAt(
      name: "CTDHUB_BINNOAI",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CTDHUB_BINNOAI>;

    deployContract(
      name: "CTDHUB_BINNOAI",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CTDHUB_BINNOAI>;

    deployContract(
      name: "CTDHUB_BINNOAI",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CTDHUB_BINNOAI>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
