/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

// Arquivo básico para typechain-types - build simplificado
// CTDQuizBurner deployed at 0xB5e0393E1D8E95bF5cf4fd11b03abD03855eB958

// Types básicos para compatibilidade
export interface ContractInterface {
  address: string;
}

// Re-export do contrato principal se disponível
// export type { CTDQuizBurner } from "./contracts/CTDQuizBurner";
// export { CTDQuizBurner__factory } from "./factories/contracts/CTDQuizBurner__factory";
